name: AnarchyCore
main: com.tripu1404.anarchycore.AnarchyCore
version: 1.0.0
api: ["1.0.13"]
author: tripu1404
description: Core completo para Anarchy (Dupes, Anti-32k, Anti-Illegal, Anti-Burrow, Elytra Limiter)
permissions:
   anarchy.admin:
      description: "Permiso de administrador para el core"
      default: op
