name: AnarchyCore
main: com.tripu1404.anarchycore.AnarchyCore
version: 1.0.0
api: ["1.0.13"]
author: tripu1404
description: Core completo para Anarchy (Dupes, Anti-Illegal, RTP, Elytra HUD)
permissions:
   anarchy.admin:
      description: "Permiso de administrador para el core"
      default: op
commands:
   setrtpradius:
      description: "Cambia el radio del Random Spawn (RTP)"
      usage: "/setrtpradius <bloques>"
      permission: anarchy.admin
